name: bottle_crm
description: A new Flutter project.

publish_to: 'none'

version: 1.0.16+16

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  http: ^1.3.0
  file_picker: ^9.2.2
  connectivity_plus: ^6.1.3
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  flutter_styled_toast: ^2.2.1
  dropdown_search: ^6.0.2
  textfield_tags: ^3.0.1
  multiselect_formfield: ^0.1.7
  flutter_quill: ^11.2.0
  flutter_swipe_detector: ^2.0.0
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/new_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
